### ISSUE TITLE
Issues on first install

### ISSUE THREAD

**Issue by abhayvatsa** [galbacarys/dotfiles#2]
SyntasticStatuslineFlag() and the jay color scheme should be installed before .vimrc runs. Otherwise the .vimrc won't work on first run.

**Comment by galbacarys** [comment]
Closing as invalid. These are going to happen no matter what due to the nature of using a plugin manager like Vundle. A few things will error out spectacularly the first time you open Vim, but the moment you run :BundleInstall (as helpfully stated in the instructions 🙃 ) all the error messages will go away.

tl;dr ignore, run :BundleInstall, restart vim, be happy.
